### ISSUE TITLE
Passing an empty perfix leaves the tap zombie

### ISSUE THREAD

**Issue by dcereijodo** [dcereijodo/tap-s3-json#6]
Whenever a empty prefix is passed to the tap, the tap will trigger an error as expected, but the it won't shut down with exit status 1.
```bash
target/universal/stage/bin/tap-s3-json --tap.bucket_name ryft-public-sample-data --tap.prefix "" --region us-east-1

Exception in thread "main" com.pagantis.singer.taps.exceptions.InvalidPrefixException
	at com.pagantis.singer.taps.ObjectKeyUtils.buildS3Prefix(ObjectKeyUtils.scala:10)
	at com.pagantis.singer.taps.ObjectKeyUtils.buildS3Prefix$(ObjectKeyUtils.scala:7)
	at com.pagantis.singer.taps.S3Source.buildS3Prefix(S3Source.scala:30)
	at com.pagantis.singer.taps.S3Source.object_keys(S3Source.scala:45)
	at com.pagantis.singer.taps.S3Source.object_contents(S3Source.scala:57)
	at com.pagantis.singer.taps.TapS3Json$.delayedEndpoint$com$pagantis$singer$taps$TapS3Json$1(TapS3Json.scala:28)
	at com.pagantis.singer.taps.TapS3Json$delayedInit$body.apply(TapS3Json.scala:12)
	at scala.Function0.apply$mcV$sp(Function0.scala:34)
	at scala.Function0.apply$mcV$sp$(Function0.scala:34)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App.$anonfun$main$1$adapted(App.scala:76)
	at scala.collection.immutable.List.foreach(List.scala:388)
	at scala.App.main(App.scala:76)
	at scala.App.main$(App.scala:74)
	at com.pagantis.singer.taps.TapS3Json$.main(TapS3Json.scala:12)
	at com.pagantis.singer.taps.TapS3Json.main(TapS3Json.scala)
```

**Comment by dcereijodo** [comment]
Fixed on 0.0.2
